import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

# Load the feature dataset
df = pd.read_csv("stock_features_dataset.csv")

# Convert Date column to datetime
df["Date"] = pd.to_datetime(df["Date"])

# Drop rows with missing values generated by rolling features
df = df.dropna().reset_index(drop=True)

print("Dataset after dropping NA:")
print(df.shape)

# Feature columns used for prediction
features = [
    "Return",
    "MA5",
    "MA10",
    "MA20",
    "MA60",
    "Volatility",
    "Volume_change",
    "High_Low_Spread",
    "Open_Close_Change"
]

X = df[features]
y = df["Target"]

# Time-based split (important for financial data)
# Train on earlier data, test on later data
split_date = "2020-01-01"

train = df[df["Date"] < split_date]
test = df[df["Date"] >= split_date]

X_train = train[features]
y_train = train["Target"]

X_test = test[features]
y_test = test["Target"]

print("\nTraining set size:", X_train.shape)
print("Test set size:", X_test.shape)

# Standardize features (important for Logistic Regression and SVM)
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Baseline model: Logistic Regression
model = LogisticRegression(max_iter=1000)

model.fit(X_train_scaled, y_train)

# Predictions
y_pred = model.predict(X_test_scaled)
y_prob = model.predict_proba(X_test_scaled)[:, 1]

# Evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_prob)

print("\nModel Evaluation (Logistic Regression Baseline)")
print("--------------------------------------")
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("ROC-AUC:", roc_auc)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))